kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:latest
    commands:
      - docker version
      - docker-compose -f docker-compose.yml build

  - name: deploy
    image: docker:latest
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.yml down
      - docker-compose -f docker-compose.yml up -d --build

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock