kind: pipeline
type: docker
name: default

params:
  import_datetime:
    description: Fecha y hora para la importación (YYYY-MM-DD HH:mm:ss)
    default: ""


steps:
  - name: build
    image: docker:latest
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker build -t televamos-api:latest -f docker/php/Dockerfile . --build-arg APP_ENV=prod --build-arg APP_DEBUG=0


  - name: deploy
    image: docker/compose:latest
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker-compose down
      - docker-compose up -d --build
      - docker exec symfony_php php bin/console doctrine:migrations:migrate --no-interaction

  - name: check default.conf
    image: alpine
    commands:
      - if [ -d docker/nginx/conf.d/default.conf ]; then echo "default.conf es un directorio y no debería"; exit 1; fi
      - ls -l docker/nginx/conf.d/

  - name: import-gpx
    image: docker:latest
    depends_on:
      - deploy
    when:
      event: manual
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker exec symfony_php php DATETIME=${DRONE_BUILD_PARAM_IMPORT_DATETIME:-$(date '+%Y-%m-%d %H:%M:%S')} memory_limit=512M bin/console app:import-gpx "$DATETIME"

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock