kind: pipeline
type: docker
name: default

params:
  import_datetime:
    description: Fecha y hora para la importación (YYYY-MM-DD HH:mm:ss)
    default: ""

steps:
  - name: build
    image: docker:latest
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker version
      - docker build -t televamos-api:latest ./php

  - name: check mounted files
    image: docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker exec symfony_php ls -la /var/www/html
      - docker exec symfony_php cat /var/www/html/composer.json || echo "composer.json no encontrado"

  - name: deploy
    image: docker/compose:latest
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker-compose down
      - docker-compose up -d --build
      - docker exec symfony_php ls -la /var/www/html
      - docker-compose run --rm php composer install --no-interaction --optimize-autoloader
      - docker-compose run --rm php php bin/console doctrine:migrations:migrate --no-interaction

  - name: import-gpx
    image: docker:latest
    depends_on:
      - deploy
    when:
      event: manual
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker exec symfony_php php DATETIME=${DRONE_BUILD_PARAM_IMPORT_DATETIME:-$(date '+%Y-%m-%d %H:%M:%S')} memory_limit=512M bin/console app:import-gpx "$DATETIME"

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock