kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:latest
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker version
      - docker build -t televamos-api:latest ./php

  - name: deploy
    image: docker/compose:latest
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker-compose down
      - docker-compose up -d --build

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock