version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
#    volumes:
#      - ./:/var/www/html
    networks:
      - symfony_network
    environment:
      DATABASE_URL: "pgsql://symfony_user:symfony_password@symfony_postgres:5432/symfony_db"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: symfony_nginx
    ports:
      - "8000:80"
#    volumes:
#      - ./:/var/www/html:ro
    depends_on:
      - php
    networks:
      - drone-net

  db:
    image: postgres:13
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5433:5432"
    networks:
      - symfony_network
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

networks:
  drone-net:
    external: true
  symfony_network:
    driver: bridge
