version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - symfony
    environment:
      DATABASE_URL: "pgsql://symfony_user:symfony_password@db:5433/symfony_db"

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./:/var/www/html:ro
    depends_on:
      - php
    networks:
      - symfony
      - drone-net

  db:
    image: postgres:13
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5433:5432"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
  drone-net:
    external: true